# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "firewire_ohci" "usb_storage" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.loader.grub = {
    enable = true;
    extraEntriesBeforeNixOS = false;
    version = 2;
    # enableCryptodisk = true;
    devices = ["/dev/sda"];
    #extraEntries = 
    #  ''menuentry "Windows8" {
    #     insmod ntfs
    #     set root='(hd0,msdos1)'
    #     chainloader +1
    #   }''
    # ;
  };
  
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/07373cfb-67f8-4d3e-b821-a97fe52144b2";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/sdb1";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/sda5"; }
    ];


  nix.maxJobs = 4;
}
